name: Build README.md from source branch to master
on: 
  push:
    branches:
      - source
jobs:
  build-readme:
    name: Build README from source and push to master
    runs-on: ubuntu-20.04
    steps:
      - name: Printing context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_CONTEXT: ${{ toJson(job) }}
          STEPS_CONTEXT: ${{ toJson(steps) }}
          RUNNER_CONTEXT: ${{ toJson(runner) }}
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: >
          echo $GITHUB_CONTEXT
          $JOB_CONTEXT
          $STEPS_CONTEXT
          $RUNNER_CONTEXT
          $STRATEGY_CONTEXT
          | jq;
          ls -R .
      # - name: Building svg files from mermaid
      - uses: actions/checkout@v2
      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -e '.*\.md$' -e '.*\.mermaid$' | xargs)"
      - name: mermaid files changed
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: compile mermaid
        uses: neenjaw/compile-mermaid-markdown-action@master
        with:
          files: ${{ steps.getfile.outputs.files }}
          output: 'output'
        env:
          HIDE_CODEBLOCKS: 1
      - name: show changes and push
        run: | 
          git status
          git add .
          git commit -m "generated mermaid svgs"
          git push origin source:master
